
import React from 'react';
import { 
  Utensils, 
  Sofa, 
  BedDouble, 
  Droplets, 
  DoorOpen, 
  Sprout, 
  Wrench, 
  FileText,
  Sparkles,
  CalendarDays,
  CalendarRange,
  CalendarCheck,
  CalendarHeart,
  CalendarClock
} from 'lucide-react';
import { User, Task, Category, Frequency, Language, LibraryTask } from './types';

export const USERS: User[] = [
  { id: 'user1', name: 'Priscille', color: '#0EA5E9', avatar: 'https://picsum.photos/seed/priscille/100' },
  { id: 'user2', name: 'Steve', color: '#D946EF', avatar: 'https://picsum.photos/seed/steve/100' },
];

export const CATEGORY_METADATA = {
  [Category.KITCHEN]: { icon: <Utensils />, color: 'bg-orange-100 text-orange-600', labels: { fr: 'Cuisine', en: 'Kitchen' } },
  [Category.LIVING]: { icon: <Sofa />, color: 'bg-indigo-100 text-indigo-600', labels: { fr: 'Salon & Multi', en: 'Living & Media' } },
  [Category.BEDROOMS]: { icon: <BedDouble />, color: 'bg-purple-100 text-purple-600', labels: { fr: 'Chambres', en: 'Bedrooms' } },
  [Category.BATHROOMS]: { icon: <Droplets />, color: 'bg-blue-100 text-blue-600', labels: { fr: 'Salles d’eau', en: 'Bathrooms' } },
  [Category.ENTRY]: { icon: <DoorOpen />, color: 'bg-amber-100 text-amber-600', labels: { fr: 'Entrée & Couloir', en: 'Entry & Hall' } },
  [Category.OUTDOOR]: { icon: <Sprout />, color: 'bg-emerald-100 text-emerald-600', labels: { fr: 'Terrasse & Potager', en: 'Garden & Terrace' } },
  [Category.GENERAL]: { icon: <Wrench />, color: 'bg-slate-100 text-slate-600', labels: { fr: 'Entretien Global', en: 'Global Maintenance' } },
  [Category.ADMIN]: { icon: <FileText />, color: 'bg-rose-100 text-rose-600', labels: { fr: 'Admin & Appro', en: 'Admin & Supply' } },
};

export const TASK_LIBRARY: LibraryTask[] = [
  // --- QUOTIDIEN ---
  { id: 'lib1', title: 'Arroser le potager', category: Category.OUTDOOR, suggestedFrequency: Frequency.DAILY },
  { id: 'lib2', title: "Changer l'eau des fleurs", category: Category.LIVING, suggestedFrequency: Frequency.DAILY },
  { id: 'lib3', title: 'Changer les serviettes', category: Category.BATHROOMS, suggestedFrequency: Frequency.DAILY },
  { id: 'lib4', title: 'Essuyer les miroirs (appoint)', category: Category.BATHROOMS, suggestedFrequency: Frequency.DAILY },
  { id: 'lib5', title: 'Essuyer plans de travail', category: Category.KITCHEN, suggestedFrequency: Frequency.DAILY },
  { id: 'lib6', title: 'Gérer le lave-vaisselle', category: Category.KITCHEN, suggestedFrequency: Frequency.DAILY },
  { id: 'lib7', title: 'Faire les lits', category: Category.BEDROOMS, suggestedFrequency: Frequency.DAILY },
  { id: 'lib8', title: 'Nettoyer la table repas', category: Category.KITCHEN, suggestedFrequency: Frequency.DAILY },
  { id: 'lib9', title: 'Nettoyer table basse', category: Category.LIVING, suggestedFrequency: Frequency.DAILY },
  { id: 'lib10', title: 'Nettoyer les lavabos', category: Category.BATHROOMS, suggestedFrequency: Frequency.DAILY },
  { id: 'lib11', title: 'Préparer les repas', category: Category.KITCHEN, suggestedFrequency: Frequency.DAILY },
  { id: 'lib12', title: 'Nettoyer détritus terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.DAILY },
  { id: 'lib13', title: 'Ramasser objets traînants', category: Category.LIVING, suggestedFrequency: Frequency.DAILY },
  { id: 'lib14', title: 'Ranger entrée (chaussures)', category: Category.ENTRY, suggestedFrequency: Frequency.DAILY },
  { id: 'lib15', title: 'Ranger coussins/plaids', category: Category.LIVING, suggestedFrequency: Frequency.DAILY },
  { id: 'lib16', title: 'Ranger les courses', category: Category.KITCHEN, suggestedFrequency: Frequency.DAILY },
  { id: 'lib17', title: 'Ranger les vêtements', category: Category.BEDROOMS, suggestedFrequency: Frequency.DAILY },
  { id: 'lib18', title: 'Vider poubelle cuisine', category: Category.KITCHEN, suggestedFrequency: Frequency.DAILY },
  { id: 'lib19', title: 'Vider poubelles SDB/WC', category: Category.BATHROOMS, suggestedFrequency: Frequency.DAILY },

  // --- HEBDOMADAIRE ---
  { id: 'lib20', title: 'Arroser plantes intérieur', category: Category.LIVING, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib21', title: 'Balayer le couloir entrée', category: Category.ENTRY, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib22', title: 'Changer les draps', category: Category.BEDROOMS, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib23', title: 'Composter les déchets', category: Category.OUTDOOR, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib24', title: 'Dépoussiérer les meubles', category: Category.LIVING, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib25', title: 'Désherber le potager', category: Category.OUTDOOR, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib26', title: 'Détartrer les robinets', category: Category.BATHROOMS, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib27', title: 'Faire les courses', category: Category.ADMIN, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib28', title: 'Laver le sol (serpillière)', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib29', title: 'Laver serviettes de bain', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib30', title: 'Laver tapis de bain', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib31', title: 'Nettoyer intérieur frigo', category: Category.KITCHEN, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib32', title: 'Nettoyer évier & bonde', category: Category.KITCHEN, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib33', title: 'Nettoyer TV & Projecteur', category: Category.LIVING, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib34', title: 'Nettoyer la baignoire', category: Category.BATHROOMS, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib35', title: 'Nettoyer plaques/cuisinière', category: Category.KITCHEN, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib36', title: 'Nettoyer la douche', category: Category.BATHROOMS, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib37', title: 'Nettoyer table & chaises', category: Category.LIVING, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib38', title: 'Nettoyer micro-ondes', category: Category.KITCHEN, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib39', title: 'Nettoyer les WC complet', category: Category.BATHROOMS, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib40', title: 'Nettoyer poignées/interr.', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib41', title: 'Nettoyer vitres (appoint)', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib42', title: 'Aspirateur tout appart', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib43', title: 'Balayer la terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib44', title: 'Planifier menus semaine', category: Category.ADMIN, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib45', title: 'Ranger chambre jeux', category: Category.BEDROOMS, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib46', title: 'Récolter les légumes', category: Category.OUTDOOR, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib47', title: 'Sortir les poubelles', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib48', title: 'Tailler les plantes', category: Category.OUTDOOR, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib49', title: 'Trier le recyclage', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib50', title: 'Nettoyer poubelles tri', category: Category.GENERAL, suggestedFrequency: Frequency.WEEKLY },
  { id: 'lib51', title: 'Vérifier santé plantes', category: Category.OUTDOOR, suggestedFrequency: Frequency.WEEKLY },

  // --- MENSUEL ---
  { id: 'lib52', title: 'Archiver documents admin', category: Category.ADMIN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib53', title: 'Changer ampoules HS', category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib54', title: "Acheter produits entretien", category: Category.ADMIN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib55', title: 'Dégivrer congélateur', category: Category.KITCHEN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib56', title: 'Hauts de meubles/biblio', category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib57', title: 'Dépoussiérer les livres', category: Category.LIVING, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib58', title: 'Détartrer bouilloire/café', category: Category.KITCHEN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib59', title: 'Faire le budget mensuel', category: Category.ADMIN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib60', title: 'Fertiliser le potager', category: Category.OUTDOOR, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib61', title: 'Laver rideaux / stores', category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib62', title: 'Nettoyer four profondeur', category: Category.KITCHEN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib63', title: 'Nettoyer le Home Cinéma', category: Category.LIVING, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib64', title: 'Nettoyer lave-linge', category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib65', title: 'Nettoyer lave-vaisselle', category: Category.KITCHEN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib66', title: 'Lentille projecteur', category: Category.LIVING, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib67', title: 'Consoles de jeux & pads', category: Category.BEDROOMS, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib68', title: 'Nettoyer filtres LV', category: Category.KITCHEN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib69', title: "Grilles d'aération VMC", category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib70', title: 'Nettoyer jouets & bibelots', category: Category.BEDROOMS, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib71', title: 'Nettoyer lustres/lampes', category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib72', title: 'Meubles de terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib73', title: 'Miroirs en profondeur', category: Category.BATHROOMS, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib74', title: 'Intérieur placards cuisine', category: Category.KITCHEN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib75', title: "Nettoyer porte d'entrée", category: Category.ENTRY, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib76', title: 'Nettoyer stores extérieurs', category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib77', title: 'Vitres de terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib78', title: 'Payer factures/loyer', category: Category.ADMIN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib79', title: 'Ranger DVD & Biblio', category: Category.LIVING, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib80', title: 'Ranger câbles & tech', category: Category.GENERAL, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib81', title: 'Retourner le compost', category: Category.OUTDOOR, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib82', title: 'Sauvegarder photos/docs', category: Category.ADMIN, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib83', title: 'Tailler arbustes terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib84', title: 'Trier meuble chaussures', category: Category.ENTRY, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib85', title: 'Gouttières terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.MONTHLY },
  { id: 'lib86', title: 'Inventaire stocks ménage', category: Category.ADMIN, suggestedFrequency: Frequency.MONTHLY },

  // --- ANNUEL / SAISONNIER ---
  { id: 'lib87', title: 'Piles détecteurs fumée', category: Category.GENERAL, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib88', title: 'Ramonage / Vérification', category: Category.GENERAL, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib89', title: 'Grand ménage printemps', category: Category.GENERAL, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib90', title: 'Laver coussins terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib91', title: 'Fenêtres extérieures', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib92', title: 'Laver les oreillers', category: Category.BEDROOMS, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib93', title: 'Shampouiner tapis', category: Category.GENERAL, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib94', title: 'Mise à jour inventaire', category: Category.ADMIN, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib95', title: 'Nettoyer derrière frigo', category: Category.KITCHEN, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib96', title: 'Nettoyer le barbecue', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib97', title: 'Évacuations terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib98', title: 'Nettoyer les matelas', category: Category.BEDROOMS, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib99', title: 'Nettoyer outils jardin', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib100', title: 'Nettoyer ventilateurs', category: Category.GENERAL, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib101', title: 'Pailler le potager', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib102', title: 'Planifier vacances', category: Category.ADMIN, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib103', title: 'Préparer sol potager', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib104', title: 'Rentrer plantes frileuses', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib105', title: 'Récolte finale (Automne)', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib106', title: 'Semis & nouvelles plantes', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib107', title: 'Traiter nuisibles jardin', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib108', title: 'Dons vêtements / Tri', category: Category.BEDROOMS, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib109', title: 'Vider placards chaussures', category: Category.ENTRY, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib110', title: 'Vérifier assurances', category: Category.ADMIN, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib111', title: 'Nettoyer hotte (filtre)', category: Category.KITCHEN, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib112', title: 'Vérifier bibliothèque', category: Category.LIVING, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib113', title: 'Éclairage terrasse', category: Category.OUTDOOR, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib114', title: 'Vérifier joints sanitaires', category: Category.BATHROOMS, suggestedFrequency: Frequency.ANNUAL },
  { id: 'lib115', title: 'Vérifier extincteurs', category: Category.GENERAL, suggestedFrequency: Frequency.ANNUAL },
];

export const FREQUENCY_VIEWS = [
  { id: 'DAY', labels: { fr: 'Jour', en: 'Day' }, icon: <CalendarDays /> },
  { id: 'WEEK', labels: { fr: 'Semaine', en: 'Week' }, icon: <CalendarRange /> },
  { id: 'MONTH', labels: { fr: 'Mois', en: 'Month' }, icon: <CalendarCheck /> },
  { id: 'QUARTER', labels: { fr: 'Trimestre', en: 'Quarter' }, icon: <CalendarHeart /> },
  { id: 'YEAR', labels: { fr: 'Année', en: 'Year' }, icon: <CalendarClock /> },
];

export const FREQUENCY_LABELS: Record<string, Record<string, string>> = {
  [Frequency.DAILY]: { fr: 'Quotidien', en: 'Daily' },
  [Frequency.WEEKLY]: { fr: 'Hebdomadaire', en: 'Weekly' },
  [Frequency.MONTHLY]: { fr: 'Mensuel', en: 'Monthly' },
  [Frequency.QUARTERLY]: { fr: 'Trimestriel', en: 'Quarterly' },
  [Frequency.ANNUAL]: { fr: 'Annuel', en: 'Annual' },
};

export const TRANSLATIONS = {
  fr: {
    welcome: "Bienvenue sur Audi",
    activateVoice: "Activez l'assistant vocal pour commencer la gestion de votre foyer.",
    enter: "Entrer",
    dashboard: "Tableau de Bord",
    history: "Historique",
    activities: "Activités Ménage",
    settings: "Paramètres",
    member: "Membre",
    hello: "Bonjour le foyer",
    historyStats: "Historique & Stats",
    householdSettings: "Paramètres du foyer",
    activitiesTitle: "Bibliothèque d'Activités",
    activitiesSearch: "Rechercher une tâche...",
    newTask: "Nouvelle Tâche",
    assistantActive: "Assistant actif",
    todayProgress: "Progression d'aujourd'hui",
    tasksCompleted: "tâches terminées",
    globalRate: "Taux global",
    tasksOf: "Tâches",
    all: "Tout",
    sos: "SOS",
    contributors: "Contributeurs",
    byCategory: "Par Catégorie",
    householdState: "État du foyer",
    lastCompleted: "Dernières complétions",
    historyEmpty: "Historique vide",
    profiles: "Profils",
    personalize: "Personnaliser",
    editProfile: "Édition Profil",
    nickname: "Prénom / Surnom",
    signatureColor: "Couleur Signature",
    cancel: "Annuler",
    save: "Enregistrer",
    taskTitle: "Intitulé",
    taskPlaceholder: "Qu'y a-t-il à faire ?",
    category: "Catégorie",
    recurrence: "Récurrence",
    assign: "Attribuer",
    addTask: "Ajouter la tâche",
    dropZone: "Déposer ici",
    dropZoneWin: "Lâchez pour gagner !",
    done: "C'est fait",
    finish: "Terminer",
    urgent: "URGENT",
    help: "AIDE",
    reassign: "Réattribuer",
    delete: "Supprimer",
    briefingTitle: "Briefing d'Audi",
    deleteConfirm: "Voulez-vous vraiment supprimer cette tâche ?",
    system: "Système",
    resetData: "Réinitialiser",
    exportData: "Exporter (JSON)",
    importData: "Importer (JSON)",
    confirmReset: "Êtes-vous sûr ?",
    dataExported: "Données exportées !",
    dataImported: "Données importées avec succès !",
    dataImportError: "Erreur lors de l'importation. Format invalide.",
    dataReset: "Données réinitialisées.",
    addToBoard: "Ajouter au planning",
    taskAdded: "Tâche ajoutée avec succès !",
    noTasksFound: "Aucune activité trouvée.",
    late: "En retard",
    threeDaysLate: "3j+",
    importPlaceholder: "Collez le JSON ici...",
    changePhoto: "Changer la photo",
    uploadHelp: "Cliquez sur l'avatar pour charger une image",
    filteredBy: "Filtré par",
    filterAll: "Toutes les tâches"
  },
  en: {
    welcome: "Welcome to Audi",
    activateVoice: "Activate voice assistant to start.",
    enter: "Enter",
    dashboard: "Dashboard",
    history: "History",
    activities: "Housekeeping",
    settings: "Settings",
    member: "Member",
    hello: "Hello Home",
    historyStats: "History & Stats",
    householdSettings: "Home Settings",
    activitiesTitle: "Activity Library",
    activitiesSearch: "Search for a task...",
    newTask: "New Task",
    assistantActive: "Assistant active",
    todayProgress: "Today's Progress",
    tasksCompleted: "tasks completed",
    globalRate: "Global rate",
    tasksOf: "Tasks",
    all: "All",
    sos: "SOS",
    contributors: "Contributors",
    byCategory: "By Category",
    householdState: "Home State",
    lastCompleted: "Last completions",
    historyEmpty: "History empty",
    profiles: "Profiles",
    personalize: "Personalize",
    editProfile: "Edit Profile",
    nickname: "Nickname",
    signatureColor: "Signature Color",
    cancel: "Cancel",
    save: "Save",
    taskTitle: "Title",
    taskPlaceholder: "What needs to be done?",
    category: "Category",
    recurrence: "Recurrence",
    assign: "Assign",
    addTask: "Add Task",
    dropZone: "Drop here",
    dropZoneWin: "Let go to win!",
    done: "Done",
    finish: "Finish",
    urgent: "URGENT",
    help: "HELP",
    reassign: "Reassign",
    delete: "Delete",
    briefingTitle: "Audi Briefing",
    deleteConfirm: "Delete this task?",
    system: "System",
    resetData: "Reset Data",
    exportData: "Export (JSON)",
    importData: "Import (JSON)",
    confirmReset: "Are you sure?",
    dataExported: "Data exported!",
    dataImported: "Data imported successfully!",
    dataImportError: "Import error. Invalid format.",
    dataReset: "Data reset successfully.",
    addToBoard: "Add to board",
    taskAdded: "Task successfully added!",
    noTasksFound: "No activities found.",
    late: "Late",
    threeDaysLate: "3d+",
    importPlaceholder: "Paste JSON here...",
    changePhoto: "Change photo",
    uploadHelp: "Click on avatar to upload image",
    filteredBy: "Filtered by",
    filterAll: "All tasks"
  }
};

export const INITIAL_TASKS: Task[] = [
  {
    id: '1',
    title: 'Laver la vaisselle',
    category: Category.KITCHEN,
    frequency: Frequency.DAILY,
    assignedTo: ['user1'],
    completedBy: [],
    isSOS: false,
    dueDate: new Date().toISOString(),
    isDone: false,
    lastResetAt: new Date().toISOString()
  }
];
